name: On Code Change (PR)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    container:
      image: node:lts-alpine

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: yarn set version stable
      - run: yarn
      - run: yarn run lint

  build:
    needs: [lint]
    name: Build
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    container:
      image: node:lts-alpine

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: yarn set version stable
      - run: yarn
      - run: yarn jahia-pack

  test:
    needs: [build]
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:lts-alpine

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: yarn install
      - run: yarn test